Models/Schedule.cs
using System.ComponentModel.DataAnnotations;

namespace CampusFlow.Models
{
    public enum WeekType
    {
        Odd,
        Even
    }
    public class Schedule
    {
        [Key]
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int TimeSlotId { get; set; }
        public DayOfWeek DayOfWeek { get; set; }
        public WeekType WeekType { get; set; }

        public int? SemesterId { get; set; }
        public int GroupId { get; set; }

        public virtual Class Class { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Semester? Semester { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<ScheduleDate> ScheduleDates { get; set; }

    }
}

ViewModels/ScheduleViewModel.cs
using CampusFlow.Models;

namespace CampusFlow.ViewModels
{
    public class ScheduleViewModel
    {
        public string ClassName { get; set; }
        public DayOfWeek DayOfWeek { get; set; }
        public TimeSlot TimeSlot { get; set; }
        public int GroupId { get; set; }
        public string TeacherName { get; set; }
        public string ClassType { get; set; }
        public string Location { get; set; }
        public int ScheduleDateId { get; set; }
    }
}

Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampusFlow.Data;
using CampusFlow.Models;

namespace CampusFlow.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly CampusContext _context;

        public AttendanceController(CampusContext context)
        {
            _context = context;
        }

        // GET: Attendances
        public async Task<IActionResult> Index(int scheduleDateId, int groupId)
        {
            if (!await _context.Attendances.AnyAsync(a => a.ScheduleDateId == scheduleDateId))
            {
                var students = await _context.Students
                    .Where(s => s.GroupId == groupId)
                    .ToListAsync();
                var newAttends = new List<Attendance>();
                foreach (var student in students)
                {
                    newAttends.Add(new Attendance()
                    {
                        ScheduleDateId = scheduleDateId,
                        StudentId = student.Id,
                        IsPresent = true
                    });
                }

                await _context.AddRangeAsync(newAttends);
                await _context.SaveChangesAsync();
            }

            var attends = await _context.Attendances
                .Where(a => a.ScheduleDateId == scheduleDateId)
                .Include(a => a.Student)
                .ToListAsync();

            ViewData["ScheduleInfo"] = await _context.ScheduleDates
                .Where(sd => sd.Id == scheduleDateId)
                .Include(sd => sd.Schedule)
                    .ThenInclude(s => s.Class)
                .SingleOrDefaultAsync();

            ViewData["Group"] = await _context.Groups.SingleOrDefaultAsync(g => g.Id == groupId);

            return View(attends);
        }


        public async Task<IActionResult> UpdateAll(int scheduleDateId, int groupId, Dictionary<int, bool> attendanceStatuses)
        {
            if (attendanceStatuses != null)
            {
                foreach (var attendanceStatus in attendanceStatuses)
                {
                    var attendance = await _context.Attendances.SingleOrDefaultAsync(a => a.StudentId == attendanceStatus.Key 
                                                && a.ScheduleDateId == scheduleDateId);
                    attendance.IsPresent = attendanceStatus.Value;
                    _context.Entry(attendance).State = EntityState.Modified;
                }

                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", new { scheduleDateId = scheduleDateId, groupId = groupId });
        }

        // GET: Attendances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Attendances == null)
            {
                return NotFound();
            }

            var attendance = await _context.Attendances.FindAsync(id);
            if (attendance == null)
            {
                return NotFound();
            }
            return View(attendance);
        }

        // POST: Attendances/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ScheduleId,StudentId")] Attendance attendance)
        {
            if (id != attendance.Id)
            {
                return NotFound();
            }

            ModelState.Remove("Class");
            ModelState.Remove("Student");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attendance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttendancesExists(attendance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(attendance);
        }

        // GET: Attendances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Attendances == null)
            {
                return NotFound();
            }

            var attendance = await _context.Attendances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }

            return View(attendance);
        }

        // POST: Attendances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Attendances == null)
            {
                return Problem("Entity set 'CampusContext.Attendances'  is null.");
            }
            var attendance = await _context.Attendances.FindAsync(id);
            if (attendance != null)
            {
                _context.Attendances.Remove(attendance);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttendancesExists(int id)
        {
          return (_context.Attendances?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampusFlow.Data;
using CampusFlow.Models;
using CampusFlow.ViewModels;
using CampusFlow.Extensions;
using System.Globalization;

namespace CampusFlow.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly CampusContext _context;

        public ScheduleController(CampusContext context)
        {
            _context = context;
        }

        // GET: Schedule
        public async Task<IActionResult> Index(int? groupSelected, DateTime startDate, 
            string weekMove, WeekType weekTypeSelected = 0)
        {
            if (startDate == default(DateTime))
            {
                startDate = DateTime.Today.DateByWeekDay(DayOfWeek.Monday);
            }

            if (!string.IsNullOrEmpty(weekMove))
            {
                startDate = (weekMove.Equals("Forward")) ? startDate.AddDays(7) : startDate.AddDays(-7);
            }

            var endDate = startDate.AddDays(6);

            ViewData["CurrentDates"] = Enumerable.Range(0, (endDate - startDate).Days + 1)
                                                 .Select(d => startDate.AddDays(d))
                                                 .ToList();
            ViewData["Groups"] = new SelectList(_context.Groups, "Id", "Name", groupSelected);
            ViewData["SelectedWeekType"] = weekTypeSelected;
            ViewData["StartDate"] = startDate;

            var currentWeekSchedule = await _context.Schedules
                .Where(s => s.Group.Id == (groupSelected ?? 8) && s.WeekType == weekTypeSelected)
                .Include(s => s.ScheduleDates.Where(sd => sd.Date >= startDate && sd.Date <= endDate))
                .Include(s => s.TimeSlot)
                .Include(s => s.Class)
                    .ThenInclude(c => c.Teacher)
                .ToListAsync();

            foreach (var currentSchedule in currentWeekSchedule)
            {
                if (!currentSchedule.ScheduleDates.Any())
                {
                    var currentDate = startDate.AddDays((int) currentSchedule.DayOfWeek - 1);
                    var scheduleDate = new ScheduleDate()
                    {
                        ScheduleId = currentSchedule.Id,
                        Date = currentDate
                    };

                    await _context.AddAsync(scheduleDate);
                    await _context.SaveChangesAsync();

                    
                }
            }

            ViewData["TimeSlots"] = await _context.TimeSlot.ToListAsync();
            var currentWeekScheduleViewModel = currentWeekSchedule.Select(s => new ScheduleViewModel
            {
                ClassName = s.Class.Name,
                DayOfWeek = s.DayOfWeek,
                TimeSlot = s.TimeSlot,
                GroupId = s.GroupId,
                TeacherName = s.Class.Teacher.FullName,
                ClassType = s.Class.ClassType.ToString(),
                Location = s.Class.Location,
                ScheduleDateId = s.ScheduleDates.Select(sd => sd.Id).SingleOrDefault(),
            }).ToList();

            return View(currentWeekScheduleViewModel);
        }

        public async Task<IActionResult> EditableIndex(int? groupSelected, WeekType weekTypeSelected)
        {
            ViewData["Days"] = EditableScheduleViewModel.Days;
            ViewData["Groups"] = new SelectList(_context.Groups, "Id", "Name", groupSelected);
            ViewData["SelectedWeekType"] = weekTypeSelected;

            var schedules = _context.Schedules
                .Where(s => s.Group.Id == (groupSelected ?? 8) && s.WeekType == weekTypeSelected)
                .Include(s => s.TimeSlot)
                .Include(s => s.Class)
                .OrderBy(s => s.DayOfWeek);
            
            var timeslots = await _context.TimeSlot.ToListAsync();
            var viewModelList = new List<EditableScheduleViewModel>();

            foreach (var item in timeslots)
            {
                viewModelList.Add(new EditableScheduleViewModel(await schedules.Where(s => s.TimeSlotId == item.Id).ToListAsync(),
                    item));
            }
            return View(viewModelList);
        }


        // GET: Schedule/Create
        public IActionResult Create()
        {
            SetScheduleViewData();
            return View();
        }

        // POST: Schedule/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClassId,TimeSlotId,DayOfWeek,WeekType,SemesterId,GroupId")] Schedule schedule)
        {
            SetScheduleViewData(schedule);

            if (ModelState.IsValid)
            {
                _context.Add(schedule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(schedule);
        }

        // GET: Schedule/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }

            SetScheduleViewData(schedule);
            return View(schedule);
        }

        // POST: Schedule/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClassId,TimeSlotId,DayOfWeek,WeekType,SemesterId,GroupId")] Schedule schedule)
        {
            if (id != schedule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schedule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleExists(schedule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            SetScheduleViewData(schedule);
            return View(schedule);
        }

        // GET: Schedule/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules
                .Include(s => s.Class)
                .Include(s => s.Group)
                .Include(s => s.Semester)
                .Include(s => s.TimeSlot)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedule/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Schedules == null)
            {
                return Problem("Entity set 'CampusContext.Schedules'  is null.");
            }
            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule != null)
            {
                _context.Schedules.Remove(schedule);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleExists(int id)
        {
          return (_context.Schedules?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public void SetScheduleViewData(Schedule schedule = null)
        {
            ModelState.Remove("Class");
            ModelState.Remove("Group");
            ModelState.Remove("Semester");
            ModelState.Remove("TimeSlot");
            ModelState.Remove("ScheduleDates");

            if (schedule == null)
            {
                ViewData["Class"] = new SelectList(_context.Classes, "Id", "Name");
                ViewData["Group"] = new SelectList(_context.Groups, "Id", "Name");
                ViewData["Semester"] = new SelectList(_context.Semesters, "Id", "Name");
                ViewData["TimeSlot"] = new SelectList(_context.TimeSlot, "Id", "Id");
                return;
            }

            ViewData["Class"] = new SelectList(_context.Classes, "Id", "Name", schedule.ClassId);
            ViewData["Groud"] = new SelectList(_context.Groups, "Id", "Name", schedule.GroupId);
            ViewData["Semester"] = new SelectList(_context.Semesters, "Id", "Name", schedule.SemesterId);
            ViewData["TimeSlot"] = new SelectList(_context.TimeSlot, "Id", "Id", schedule.TimeSlotId);
        }
    }
}

Views/Schedule/Create.cshtml
@model CampusFlow.Models.Schedule

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label">Class</label>
                <select asp-for="ClassId" class ="form-control" asp-items="ViewBag.Class"></select>
            </div>
            <div class="form-group">
                <label asp-for="TimeSlotId" class="control-label"></label>
                <select asp-for="TimeSlotId" class ="form-control" asp-items="ViewBag.TimeSlot"></select>
            </div>
            <div class="form-group">
                <label asp-for="DayOfWeek" class="control-label"></label>
                <select asp-for="DayOfWeek" class="form-control" asp-items="@Html.GetEnumSelectList<DayOfWeek>()"></select>
                <span asp-validation-for="DayOfWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeekType" class="control-label"></label>
                <select asp-for="WeekType" class="form-control" asp-items="@Html.GetEnumSelectList<WeekType>()"></select>
                <span asp-validation-for="WeekType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SemesterId" class="control-label">Semester</label>
                <select asp-for="SemesterId" class ="form-control" asp-items="ViewBag.Semester"></select>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Group</label>
                <select asp-for="GroupId" class ="form-control" asp-items="ViewBag.Group"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Schedule/Delete.cshtml
@model CampusFlow.Models.Schedule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DayOfWeek)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WeekType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WeekType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSlot.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Schedule/Details.cshtml
@model CampusFlow.Models.Schedule

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DayOfWeek)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WeekType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WeekType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSlot.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Schedule/Edit.cshtml
@model CampusFlow.Models.Schedule

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <select asp-for="ClassId" class="form-control" asp-items="ViewBag.ClassId"></select>
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSlotId" class="control-label"></label>
                <select asp-for="TimeSlotId" class="form-control" asp-items="ViewBag.TimeSlotId"></select>
                <span asp-validation-for="TimeSlotId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DayOfWeek" class="control-label"></label>
                <select asp-for="DayOfWeek" class="form-control" asp-items="ViewBag.CurrentDates"></select>
                <span asp-validation-for="DayOfWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeekType" class="control-label"></label>
                <select asp-for="WeekType" class="form-control"></select>
                <span asp-validation-for="WeekType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SemesterId" class="control-label"></label>
                <select asp-for="SemesterId" class="form-control" asp-items="ViewBag.SemesterId"></select>
                <span asp-validation-for="SemesterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Schedule/Index.cshtml
@using CampusFlow.Extensions;
@model List<ScheduleViewModel>

@{
    ViewData["Title"] = "Current Week Schedule";
    var today = DateTime.Today;
}

<div class="container mt-4">
    <h2>@ViewData["Title"]</h2>
    <a asp-action="EditableIndex">Edit schedule</a>

    <form asp-action="Index" class="col-md-4" method="get">
        <div class="form-group mt-4 d-flex">
            <label for="groupFilter">Group:</label>
            <select class="form-control" name="groupSelected" asp-items="@ViewBag.Groups">
            </select>
            <label>Week Type:</label>
            <select class="form-control" name="weekTypeSelected">
                <option value="Odd" selected="@((WeekType)ViewBag.SelectedWeekType == WeekType.Odd)">Odd</option>
                <option value="Even" selected="@((WeekType)ViewBag.SelectedWeekType == WeekType.Even)">Even</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary filter-btn">Apply Filter</button>
    </form>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th></th>
                    @foreach(var date in ViewBag.CurrentDates)
                    {
                        <th>@date.ToString("dddd, dd MMMM")</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var timeSlot in ViewBag.TimeSlots)
                {
                    <tr>
                        <td>
                            <center>
                                <h4>@timeSlot.ClassNumber</h4>
                                @timeSlot.StartTime.ToString(@"hh\:mm") - @timeSlot.EndTime.ToString(@"hh\:mm")
                            </center>
                        </td>
                        @foreach (var date in ViewBag.CurrentDates)
                        {
                            var schedule = Model.FirstOrDefault(s =>
                                s.TimeSlot.Id == timeSlot.Id &&
                                s.DayOfWeek == date.DayOfWeek);
                            <td
                            @if(date.Equals(today))
                            {
                                <text> class="active-day"</text>   
                            }
                            >
                                @if (schedule != null)
                                {
                                    <a asp-controller="Attendance" asp-action="Index"
                                        asp-route-scheduleDateId="@schedule.ScheduleDateId" asp-route-groupId="@schedule.GroupId">
                                        <div class="schedule-slot">
                                            @if (schedule != null)
                                            {
                                                <p>@schedule.ClassName</p>
                                                <p>@schedule.TeacherName</p>
                                                <p>@schedule.Location</p>
                                            }
                                        </div>
                                    </a>
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <form method="post" action="/">
        <input type="hidden" name="startDate" value="@ViewBag.StartDate"/>
        <input class="btn btn-secondary" type="submit" name="weekMove" value="Backward" />
        <input class="btn btn-secondary" type="submit" name="weekMove" value="Forward" />
    </form>

</div>